Repository swmaeStrong/pomocore-main-server, pull requests merged in 2025-06, with the labels that each got.

#40 [SWM-93, SMW-94] 비회원 등록시 반환값 추가
  src/main/java/com/swmStrong/demo/domain/loginCredential/controller/LoginCredentialController.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/entity/LoginCredential.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/repository/LoginCredentialRepository.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/user/controller/UserController.java
  src/main/java/com/swmStrong/demo/domain/user/dto/UserResponseDto.java
  src/main/java/com/swmStrong/demo/domain/user/entity/User.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserDeleteProvider.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserDeleteProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserInfoProvider.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserInfoProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserUpdateProvider.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserUpdateProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserService.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserServiceImpl.java
Labels: enhancement

#42 [SWM-54, SWM-95] Api Response 통일, 비회원 토큰 문제 해결
  src/main/java/com/swmStrong/demo/common/exception/ApiException.java
  src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
  src/main/java/com/swmStrong/demo/common/response/CustomResponseEntity.java
  src/main/java/com/swmStrong/demo/config/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/swmStrong/demo/config/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/swmStrong/demo/config/security/principal/SecurityPrincipal.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/controller/CategoryPatternController.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/service/CategoryPatternServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/controller/LeaderboardController.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/controller/LoginCredentialController.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/facade/LoginCredentialProvider.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/facade/LoginCredentialProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/usageLog/controller/UsageLogController.java
  src/main/java/com/swmStrong/demo/domain/user/controller/UserController.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserDetailsProvider.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserDetailsProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserInfoProvider.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserUpdateProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserServiceImpl.java
  src/main/java/com/swmStrong/demo/util/token/TokenUtil.java
Labels: enhancement, chore

#49 [SWM-96] 구독 갱신로직 서버에서 관리하도록 변경 및 api 추가
  src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
  src/main/java/com/swmStrong/demo/domain/subscriptionPlan/controller/SubscriptionPlanController.java
  src/main/java/com/swmStrong/demo/domain/subscriptionPlan/dto/req/SubscriptionPlanRes.java
  src/main/java/com/swmStrong/demo/domain/subscriptionPlan/entity/BillingCycle.java
  src/main/java/com/swmStrong/demo/domain/subscriptionPlan/entity/SubscriptionPlan.java
  src/main/java/com/swmStrong/demo/domain/subscriptionPlan/repository/SubscriptionPlanRepository.java
  src/main/java/com/swmStrong/demo/domain/subscriptionPlan/service/SubscriptionPlanService.java
  src/main/java/com/swmStrong/demo/domain/subscriptionPlan/service/SubscriptionPlanServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/userPaymentMethod/controller/UserPaymentMethodsController.java
  src/main/java/com/swmStrong/demo/domain/userPaymentMethod/converter/BillingKeyCryptoConverter.java
  src/main/java/com/swmStrong/demo/domain/userPaymentMethod/dto/BillingKeyReq.java
  src/main/java/com/swmStrong/demo/domain/userPaymentMethod/dto/UserPaymentMethodRes.java
  src/main/java/com/swmStrong/demo/domain/userPaymentMethod/entity/UserPaymentMethod.java
  src/main/java/com/swmStrong/demo/domain/userPaymentMethod/repository/UserPaymentMethodRepository.java
  src/main/java/com/swmStrong/demo/domain/userPaymentMethod/service/UserPaymentMethodService.java
  src/main/java/com/swmStrong/demo/domain/userPaymentMethod/service/UserPaymentMethodServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/controller/UserSubscriptionController.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/dto/ExistingUserSubscriptionReq.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/dto/NewUserSubscriptionReq.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/dto/UserSubscriptionRes.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/entity/UserSubscription.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/entity/UserSubscriptionStatus.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/repository/UserSubscriptionRepository.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/service/UserSubscriptionSchedulerService.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/service/UserSubscriptionService.java
  src/main/java/com/swmStrong/demo/domain/userSubscription/service/UserSubscriptionServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/web/service/WebhookServiceImpl.java
  src/main/java/com/swmStrong/demo/infra/portone/PortOneBillingClient.java
  src/main/java/com/swmStrong/demo/infra/portone/PortOnePaymentClient.java
  src/main/java/com/swmStrong/demo/infra/portone/PortOneScheduleClient.java
Labels: bug, enhancement, chore

#50 [SWM-98] 리더보드 쿼리 리팩토링 및 카테고리 관련 검증
  src/main/java/com/swmStrong/demo/common/annotation/HexColor.java
  src/main/java/com/swmStrong/demo/common/exception/GlobalExceptionHandler.java
  src/main/java/com/swmStrong/demo/common/response/ApiResponse.java
  src/main/java/com/swmStrong/demo/common/response/CustomResponseEntity.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/controller/CategoryPatternController.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryRequestDto.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/UpdateCategoryRequestDto.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/service/CategoryPatternServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/user/controller/UserController.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserInfoProvider.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserInfoProviderImpl.java
Labels: enhancement

#54 [SWM-72, SWM-100] 리더보드 히스토리 저장 및 소셜 로그인
  src/main/java/com/swmStrong/demo/DemoApplication.java
  src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
  src/main/java/com/swmStrong/demo/config/security/WhiteListConfig.java
  src/main/java/com/swmStrong/demo/config/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/swmStrong/demo/domain/common/enums/PeriodType.java
  src/main/java/com/swmStrong/demo/domain/common/enums/Role.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/entity/Leaderboard.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/repository/LeaderboardCache.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/repository/LeaderboardCacheImpl.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/repository/LeaderboardRepository.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/scheduler/LeaderboardSyncScheduler.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/controller/LoginCredentialController.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/dto/SocialLoginRequestDto.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/entity/LoginCredential.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/facade/LoginCredentialProvider.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/facade/LoginCredentialProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/repository/LoginCredentialRepository.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialService.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/user/dto/UserRequestDto.java
  src/main/java/com/swmStrong/demo/domain/user/entity/User.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserUpdateProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserServiceImpl.java
  src/main/java/com/swmStrong/demo/util/token/TokenType.java
  src/main/java/com/swmStrong/demo/util/token/TokenUtil.java
  src/main/java/com/swmStrong/demo/util/token/dto/SubjectResponseDto.java
Labels: enhancement, feature

#61 [SWM-104] 내 정보 조회
  src/main/java/com/swmStrong/demo/config/security/WhiteListConfig.java
  src/main/java/com/swmStrong/demo/domain/user/controller/UserController.java
  src/main/java/com/swmStrong/demo/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/swmStrong/demo/domain/user/dto/UserResponseDto.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserService.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserServiceImpl.java
Labels: feature

#64 [SWM-106] user 관리 고도화
  src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
  src/main/java/com/swmStrong/demo/config/security/WhiteListConfig.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/entity/LoginCredential.java
  src/main/java/com/swmStrong/demo/domain/user/controller/UserController.java
  src/main/java/com/swmStrong/demo/domain/user/dto/UserRequestDto.java
  src/main/java/com/swmStrong/demo/domain/user/entity/User.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserService.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserServiceImpl.java
  src/main/java/com/swmStrong/demo/util/redis/RedisUtil.java
Labels: enhancement

#66 [SWM-106] user 리팩토링 이후 요구사항
  src/main/java/com/swmStrong/demo/config/security/WhiteListConfig.java
  src/main/java/com/swmStrong/demo/config/security/principal/SecurityPrincipal.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/controller/LoginCredentialController.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/facade/LoginCredentialProvider.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/facade/LoginCredentialProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialService.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/user/controller/UserController.java
  src/main/java/com/swmStrong/demo/domain/user/dto/UserInfoResponseDto.java
  src/main/java/com/swmStrong/demo/domain/user/dto/UserResponseDto.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserDetailsProvider.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserDetailsProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserService.java
  src/main/java/com/swmStrong/demo/domain/user/service/UserServiceImpl.java
  src/main/java/com/swmStrong/demo/util/redis/RedisUtil.java
  src/main/java/com/swmStrong/demo/util/token/TokenUtil.java
  src/main/java/com/swmStrong/demo/util/token/dto/RefreshTokenRequestDto.java
Labels: enhancement

#72 [SWM-109] 사용 로그 고도화
  build.gradle
  src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
  src/main/java/com/swmStrong/demo/config/CacheConfig.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/controller/CategoryPatternController.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryPatternJSONDto.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryRequestDto.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryResponseDto.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/UpdateCategoryRequestDto.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/entity/CategoryPattern.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/enums/PatternType.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/initializer/CategoryPatternInitializer.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/repository/CustomCategoryPatternRepository.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/repository/CustomCategoryPatternRepositoryImpl.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/service/CategoryPatternService.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/service/CategoryPatternServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/consumer/LeaderboardStreamConsumer.java
  src/main/java/com/swmStrong/demo/domain/matcher/consumer/PatternMatchStreamConsumer.java
  src/main/java/com/swmStrong/demo/domain/matcher/core/PatternClassifier.java
  src/main/java/com/swmStrong/demo/domain/matcher/core/PatternMatcher.java
  src/main/java/com/swmStrong/demo/domain/matcher/core/Trie.java
  src/main/java/com/swmStrong/demo/domain/usageLog/dto/SaveUsageLogDto.java
  src/main/java/com/swmStrong/demo/domain/usageLog/entity/UsageLog.java
  src/main/java/com/swmStrong/demo/domain/usageLog/facade/UsageLogUpdateProvider.java
  src/main/java/com/swmStrong/demo/domain/usageLog/facade/UsageLogUpdateProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/usageLog/repository/UsageLogRepository.java
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/user/listener/UserLogoutEventListener.java
  src/main/java/com/swmStrong/demo/infra/LLM/GeminiClassifier.java
  src/main/java/com/swmStrong/demo/infra/LLM/LLMClassifier.java
  src/main/java/com/swmStrong/demo/infra/redis/stream/StreamConfig.java
  src/main/java/com/swmStrong/demo/message/dto/PatternClassifyMessage.java
  src/main/resources/data/category-patterns.json
Labels: enhancement, feature

#77 [SWM-112] 프롬프트 개선 및 미분류 시 로직 추가
  src/main/java/com/swmStrong/demo/domain/matcher/core/PatternClassifier.java
  src/main/java/com/swmStrong/demo/infra/LLM/GeminiClassifier.java
Labels: enhancement, chore

#79 [Refactor] 토큰 관련 에러 핸들링 변경
  src/main/java/com/swmStrong/demo/config/security/SecurityConfig.java
  src/main/java/com/swmStrong/demo/config/security/filter/TokenAuthorizationFilter.java
  src/main/java/com/swmStrong/demo/config/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/swmStrong/demo/infra/token/TokenManager.java
Labels: chore

#80 [Refactor] 사용 로그 관련 리팩토링
  src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/dto/CategoryPatternJSONDto.java
  src/main/java/com/swmStrong/demo/domain/usageLog/dto/CategoryHourlyUsageDto.java
  src/main/java/com/swmStrong/demo/domain/usageLog/dto/CategoryUsageDto.java
  src/main/java/com/swmStrong/demo/domain/usageLog/repository/UsageLogRepository.java
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
Labels: chore

#82 fix: 대소문자를 구분하고 있는 문제 해결
  src/main/java/com/swmStrong/demo/domain/matcher/core/Trie.java
Labels: bug

#87 [SWM-115, SWM-116, SW-117] 시간 관련 변경
  src/main/java/com/swmStrong/demo/DemoApplication.java
  src/main/java/com/swmStrong/demo/common/exception/GlobalExceptionHandler.java
  src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
  src/main/java/com/swmStrong/demo/config/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/swmStrong/demo/domain/common/util/TimeZoneUtil.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardService.java
  src/main/java/com/swmStrong/demo/domain/leaderboard/service/LeaderboardServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/usageLog/dto/SaveUsageLogDto.java
  src/main/java/com/swmStrong/demo/domain/usageLog/dto/UsageLogResponseDto.java
  src/main/java/com/swmStrong/demo/domain/usageLog/entity/UsageLog.java
  src/main/java/com/swmStrong/demo/domain/usageLog/repository/UsageLogRepository.java
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
  src/main/java/com/swmStrong/demo/message/dto/LeaderBoardUsageMessage.java
Labels: bug, enhancement, feature, chore

#89 [Refactor] Chores
  src/main/java/com/swmStrong/demo/common/exception/code/ErrorCode.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/controller/LoginCredentialController.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialService.java
  src/main/java/com/swmStrong/demo/domain/loginCredential/service/LoginCredentialServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserUpdateProvider.java
  src/main/java/com/swmStrong/demo/domain/user/facade/UserUpdateProviderImpl.java
Labels: chore

#94 [SWM-140] API for activity list view
  src/main/java/com/swmStrong/demo/config/security/WhiteListConfig.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/facade/CategoryProvider.java
  src/main/java/com/swmStrong/demo/domain/categoryPattern/facade/CategoryProviderImpl.java
  src/main/java/com/swmStrong/demo/domain/common/util/TimeZoneUtil.java
  src/main/java/com/swmStrong/demo/domain/usageLog/controller/UsageLogController.java
  src/main/java/com/swmStrong/demo/domain/usageLog/dto/CategorizedUsageLogDto.java
  src/main/java/com/swmStrong/demo/domain/usageLog/dto/MergedCategoryUsageLogDto.java
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogService.java
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
Labels: feature

#98 [SWM-157] 하루 단위로 최근 로그, 타임 라인 반환
  src/main/java/com/swmStrong/demo/domain/usageLog/controller/UsageLogController.java
  src/main/java/com/swmStrong/demo/domain/usageLog/dto/MergedCategoryUsageLogDto.java
  src/main/java/com/swmStrong/demo/domain/usageLog/repository/UsageLogRepository.java
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogService.java
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
Labels: enhancement

#99 refactor: 카테고리 stream 처리 중 null로 표시되는 경우 예외처리
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
Labels: enhancement

#103 [SMW-171] timeline 관련 메서드 로직 변경
  src/main/java/com/swmStrong/demo/domain/usageLog/service/UsageLogServiceImpl.java
Labels: bug
